run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - revive

linters-settings:
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck
